const provienceData = [
  {
    name: '海南',
    area: '华南大区',
  },
  {
    name: '新疆',
    area: '其他',
  },
  {
    name: '西藏',
    area: '其他',
  },
  {
    name: '内蒙古',
    area: '其他',
  },
  {
    name: '青海',
    area: '其他',
  },
  {
    name: '四川',
    area: '华西大区',
  },
  {
    name: '黑龙江',
    area: '东北大区',
  },
  {
    name: '甘肃',
    area: '华西大区',
  },
  {
    name: '云南',
    area: '华西大区',
  },
  {
    name: '广西',
    area: '华南大区',
  },
  {
    name: '湖南',
    area: '华中大区',
  },
  {
    name: '陕西',
    area: '华西大区',
  },
  {
    name: '广东',
    area: '华南大区',
  },
  {
    name: '吉林',
    area: '东北大区',
  },
  {
    name: '河北',
    area: '华北大区',
  },
  {
    name: '湖北',
    area: '华中大区',
  },
  {
    name: '贵州',
    area: '华西大区',
  },
  {
    name: '山东',
    area: '华北大区',
  },
  {
    name: '江西',
    area: '华中大区',
  },
  {
    name: '河南',
    area: '华北大区',
  },
  {
    name: '辽宁',
    area: '东北大区',
  },
  {
    name: '山西',
    area: '华北大区',
  },
  {
    name: '安徽',
    area: '华中大区',
  },
  {
    name: '福建',
    area: '华南大区',
  },
  {
    name: '浙江',
    area: '华东大区',
  },
  {
    name: '江苏',
    area: '华东大区',
  },
  {
    name: '重庆',
    area: '华西大区',
  },
  {
    name: '宁夏',
    area: '华西大区',
  },
  {
    name: '台湾',
    area: '其他',
  },
  {
    name: '北京',
    area: '华北大区',
  },
  {
    name: '天津',
    area: '华北大区',
  },
  {
    name: '上海',
    area: '华东大区',
  },
  {
    name: '香港',
    area: '其他',
  },
  {
    name: '澳门',
    area: '其他',
  },
  {
    name: '南海诸岛',
    area: '南海诸岛',
  },
];

const geoCoordMap = {
  黑龙江: [126.6433411, 45.74149323],
  吉林: [125.3154297, 43.89256287],
  辽宁: [123.4116821, 41.7966156],
  内蒙古: [111.6632996, 40.82094193],
  北京: [116.3809433, 39.9236145],
  天津: [117.2034988, 39.13111877],
  河北: [114.4897766, 38.04512787],
  山东: [117.0056, 36.6670723],
  山西: [112.5693512, 37.87111282],
  江苏: [118.7727814, 32.04761505],
  上海: [121.4692688, 31.23817635],
  浙江: [120.1592484, 30.26599503],
  福建: [119.2978134, 26.07859039],
  广东: [113.2614288, 23.11891174],
  海南: [110.3465118, 19.03179359],
  台湾: [120.960515, 23.69781],
  香港: [114.109497, 22.396428],
  澳门: [110.5440083, 21.20167546],
  河南: [113.6500473, 34.7570343],
  安徽: [117.2757034, 31.86325455],
  江西: [115.8999176, 28.67599106],
  陕西: [108.949028, 34.26168442],
  湖北: [114.2919388, 30.56751442],
  湖南: [112.9812698, 28.20082474],
  广西: [108.3117676, 22.80654335],
  宁夏: [106.2719421, 38.46800995],
  重庆: [106.5103378, 29.55817604],
  贵州: [106.7113724, 26.57687378],
  四川: [104.0817566, 30.66105652],
  云南: [102.704567, 25.04384422],
  甘肃: [95.832762, 40.067241],
  青海: [95.786324, 36.629144],
  西藏: [91.11445308, 29.64411352],
  新疆: [89.1895474, 42.95130195],
  五指山市: [110.72, 19.61],
  文昌市: [110.72, 19.61],
  琼海市: [110.46, 19.25],
  万宁市: [110.39, 18.8],
  东方市: [108.64, 19.09],
  定安县: [110.31, 19.68],
  临高县: [109.69, 19.91],
  澄迈县: [110, 19.75],
  白沙黎族自治县: [109.44, 19.23],
  江黎族自治县: [102.188043, 38.520089],
  乐东黎族自治县: [109.17, 18.73],
  保亭黎族苗族自治县: [109.7, 18.64],
  中苗族黎族自治县: [119.46, 35.42],
  海门: [121.15, 31.89],
  鄂尔多斯: [109.781327, 39.608266],
  招远: [120.38, 37.35],
  舟山: [122.207216, 29.985295],
  齐齐哈尔: [123.97, 47.33],
  盐城: [120.13, 33.38],
  赤峰: [118.87, 42.28],
  青岛: [120.33, 36.07],
  乳山: [121.52, 36.89],
  金昌: [102.188043, 38.520089],
  泉州: [118.58, 24.93],
  莱西: [120.53, 36.86],
  日照: [119.46, 35.42],
  胶南: [119.97, 35.88],
  南通: [121.05, 32.08],
  拉萨: [91.11, 29.97],
  云浮: [112.02, 22.93],
  梅州: [116.1, 24.55],
  文登: [122.05, 37.2],
  攀枝花: [101.718637, 26.582347],
  威海: [122.1, 37.5],
  承德: [117.93, 40.97],
  厦门: [118.1, 24.46],
  汕尾: [115.375279, 22.786211],
  潮州: [116.63, 23.68],
  丹东: [124.37, 40.13],
  太仓: [121.1, 31.45],
  曲靖: [103.79, 25.51],
  烟台: [121.39, 37.52],
  福州: [119.3, 26.08],
  瓦房店: [121.979603, 39.627114],
  即墨: [120.45, 36.38],
  抚顺: [123.97, 41.97],
  玉溪: [102.52, 24.35],
  张家口: [114.87, 40.82],
  阳泉: [113.57, 37.85],
  莱州: [119.942327, 37.177017],
  湖州: [120.1, 30.86],
  汕头: [116.69, 23.39],
  昆山: [120.95, 31.39],
  宁波: [121.56, 29.86],
  湛江: [110.359377, 21.270708],
  揭阳: [116.35, 23.55],
  荣成: [122.41, 37.16],
  连云港: [119.16, 34.59],
  葫芦岛: [120.836932, 40.711052],
  常熟: [120.74, 31.64],
  东莞: [113.75, 23.04],
  河源: [114.68, 23.73],
  淮安: [119.15, 33.5],
  泰州: [119.9, 32.49],
  南宁: [108.33, 22.84],
  营口: [122.18, 40.65],
  惠州: [114.4, 23.09],
  江阴: [120.26, 31.91],
  蓬莱: [120.75, 37.8],
  韶关: [113.62, 24.84],
  嘉峪关: [98.289152, 39.77313],
  广州: [113.23, 23.16],
  延安: [109.47, 36.6],
  太原: [112.53, 37.87],
  清远: [113.01, 23.7],
  中山: [113.38, 22.52],
  昆明: [102.73, 25.04],
  寿光: [118.73, 36.86],
  盘锦: [122.070714, 41.119997],
  长治: [113.08, 36.18],
  深圳: [114.07, 22.62],
  珠海: [113.52, 22.3],
  宿迁: [118.3, 33.96],
  咸阳: [108.72, 34.36],
  铜川: [109.11, 35.09],
  平度: [119.97, 36.77],
  佛山: [113.11, 23.05],
  海口: [110.35, 20.02],
  江门: [113.06, 22.61],
  章丘: [117.53, 36.72],
  肇庆: [112.44, 23.05],
  大连: [121.62, 38.92],
  临汾: [111.5, 36.08],
  吴江: [120.63, 31.16],
  石嘴山: [106.39, 39.04],
  沈阳: [123.38, 41.8],
  苏州: [120.62, 31.32],
  茂名: [110.88, 21.68],
  嘉兴: [120.76, 30.77],
  长春: [125.35, 43.88],
  胶州: [120.03336, 36.264622],
  银川: [106.27, 38.47],
  张家港: [120.555821, 31.875428],
  三门峡: [111.19, 34.76],
  锦州: [121.15, 41.13],
  南昌: [115.89, 28.68],
  柳州: [109.4, 24.33],
  三亚: [109.511909, 18.252847],
  自贡: [104.778442, 29.33903],
  阳江: [111.95, 21.85],
  泸州: [105.39, 28.91],
  西宁: [101.74, 36.56],
  宜宾: [104.56, 29.77],
  呼和浩特: [111.65, 40.82],
  成都: [104.06, 30.67],
  大同: [113.3, 40.12],
  镇江: [119.44, 32.2],
  桂林: [110.28, 25.29],
  张家界: [110.479191, 29.117096],
  宜兴: [119.82, 31.36],
  北海: [109.12, 21.49],
  西安: [108.95, 34.27],
  金坛: [119.56, 31.74],
  东营: [118.49, 37.46],
  牡丹江: [129.58, 44.6],
  遵义: [106.9, 27.7],
  绍兴: [120.58, 30.01],
  扬州: [119.42, 32.39],
  常州: [119.95, 31.79],
  潍坊: [119.1, 36.62],
  台州: [121.420757, 28.656386],
  南京: [118.78, 32.04],
  滨州: [118.03, 37.36],
  贵阳: [106.71, 26.57],
  无锡: [120.29, 31.59],
  本溪: [123.73, 41.3],
  克拉玛依: [84.77, 45.59],
  渭南: [109.5, 34.52],
  马鞍山: [118.48, 31.56],
  宝鸡: [107.15, 34.38],
  焦作: [113.21, 35.24],
  句容: [119.16, 31.95],
  徐州: [117.2, 34.26],
  衡水: [115.72, 37.72],
  包头: [110, 40.58],
  绵阳: [104.73, 31.48],
  乌鲁木齐: [87.68, 43.77],
  枣庄: [117.57, 34.86],
  杭州: [120.19, 30.26],
  淄博: [118.05, 36.78],
  鞍山: [122.85, 41.12],
  溧阳: [119.48, 31.43],
  库尔勒: [86.06, 41.68],
  安阳: [114.35, 36.1],
  开封: [114.35, 34.79],
  济南: [117, 36.65],
  德阳: [104.37, 31.13],
  温州: [120.65, 28.01],
  九江: [115.97, 29.71],
  邯郸: [114.47, 36.6],
  临安: [119.72, 30.23],
  兰州: [103.73, 36.03],
  沧州: [116.83, 38.33],
  临沂: [118.35, 35.05],
  南充: [106.110698, 30.837793],
  富阳: [119.95, 30.07],
  泰安: [117.13, 36.18],
  诸暨: [120.23, 29.71],
  郑州: [113.65, 34.76],
  哈尔滨: [126.63, 45.75],
  聊城: [115.97, 36.45],
  芜湖: [118.38, 31.33],
  唐山: [118.02, 39.63],
  平顶山: [113.29, 33.75],
  邢台: [114.48, 37.05],
  德州: [116.29, 37.45],
  济宁: [116.59, 35.38],
  荆州: [112.239741, 30.335165],
  宜昌: [111.3, 30.7],
  义乌: [120.06, 29.32],
  丽水: [119.92, 28.45],
  洛阳: [112.44, 34.7],
  秦皇岛: [119.57, 39.95],
  株洲: [113.16, 27.83],
  石家庄: [114.48, 38.03],
  莱芜: [117.67, 36.19],
  常德: [111.69, 29.05],
  保定: [115.48, 38.85],
  湘潭: [112.91, 27.87],
  金华: [119.64, 29.12],
  岳阳: [113.09, 29.37],
  长沙: [113, 28.21],
  衢州: [118.88, 28.97],
  廊坊: [116.7, 39.53],
  菏泽: [115.480656, 35.23375],
  合肥: [117.27, 31.86],
  武汉: [114.31, 30.52],
  大庆: [125.03, 46.58],
};
const regionData = [
  {
    value: '区域',
    label: '全部',
    code: '区域',
  },
  {
    adcode: '110000',
    name: '北京市',
    children: [
      {
        parentAdcode: '110000',
        adcode: '110100',
        name: '北京市市辖区',
        p_name: '北京市',
        label: '北京市市辖区',
        value: '北京市市辖区',
      },
    ],
    label: '北京市',
    value: '北京市',
  },
  {
    adcode: '120000',
    name: '天津市',
    children: [
      {
        parentAdcode: '120000',
        adcode: '120100',
        name: '天津市市辖区',
        p_name: '天津市',
        label: '天津市市辖区',
        value: '天津市市辖区',
      },
      {
        parentAdcode: '120000',
        adcode: '120200',
        name: '天津市郊县',
        p_name: '天津市',
        label: '天津市郊县',
        value: '天津市郊县',
      },
    ],
    label: '天津市',
    value: '天津市',
  },
  {
    adcode: '130000',
    name: '河北省',
    children: [
      {
        parentAdcode: '130000',
        adcode: '130100',
        name: '石家庄市',
        p_name: '河北省',
        label: '石家庄市',
        value: '石家庄市',
      },
      {
        parentAdcode: '130000',
        adcode: '130200',
        name: '唐山市',
        p_name: '河北省',
        label: '唐山市',
        value: '唐山市',
      },
      {
        parentAdcode: '130000',
        adcode: '130300',
        name: '秦皇岛市',
        p_name: '河北省',
        label: '秦皇岛市',
        value: '秦皇岛市',
      },
      {
        parentAdcode: '130000',
        adcode: '130400',
        name: '邯郸市',
        p_name: '河北省',
        label: '邯郸市',
        value: '邯郸市',
      },
      {
        parentAdcode: '130000',
        adcode: '130500',
        name: '邢台市',
        p_name: '河北省',
        label: '邢台市',
        value: '邢台市',
      },
      {
        parentAdcode: '130000',
        adcode: '130600',
        name: '保定市',
        p_name: '河北省',
        label: '保定市',
        value: '保定市',
      },
      {
        parentAdcode: '130000',
        adcode: '130700',
        name: '张家口市',
        p_name: '河北省',
        label: '张家口市',
        value: '张家口市',
      },
      {
        parentAdcode: '130000',
        adcode: '130800',
        name: '承德市',
        p_name: '河北省',
        label: '承德市',
        value: '承德市',
      },
      {
        parentAdcode: '130000',
        adcode: '130900',
        name: '沧州市',
        p_name: '河北省',
        label: '沧州市',
        value: '沧州市',
      },
      {
        parentAdcode: '130000',
        adcode: '131000',
        name: '廊坊市',
        p_name: '河北省',
        label: '廊坊市',
        value: '廊坊市',
      },
      {
        parentAdcode: '130000',
        adcode: '131100',
        name: '衡水市',
        p_name: '河北省',
        label: '衡水市',
        value: '衡水市',
      },
    ],
    label: '河北省',
    value: '河北省',
  },
  {
    adcode: '140000',
    name: '山西省',
    children: [
      {
        parentAdcode: '140000',
        adcode: '140100',
        name: '太原市',
        p_name: '山西省',
        label: '太原市',
        value: '太原市',
      },
      {
        parentAdcode: '140000',
        adcode: '140200',
        name: '大同市',
        p_name: '山西省',
        label: '大同市',
        value: '大同市',
      },
      {
        parentAdcode: '140000',
        adcode: '140300',
        name: '阳泉市',
        p_name: '山西省',
        label: '阳泉市',
        value: '阳泉市',
      },
      {
        parentAdcode: '140000',
        adcode: '140400',
        name: '长治市',
        p_name: '山西省',
        label: '长治市',
        value: '长治市',
      },
      {
        parentAdcode: '140000',
        adcode: '140500',
        name: '晋城市',
        p_name: '山西省',
        label: '晋城市',
        value: '晋城市',
      },
      {
        parentAdcode: '140000',
        adcode: '140600',
        name: '朔州市',
        p_name: '山西省',
        label: '朔州市',
        value: '朔州市',
      },
      {
        parentAdcode: '140000',
        adcode: '140700',
        name: '晋中市',
        p_name: '山西省',
        label: '晋中市',
        value: '晋中市',
      },
      {
        parentAdcode: '140000',
        adcode: '140800',
        name: '运城市',
        p_name: '山西省',
        label: '运城市',
        value: '运城市',
      },
      {
        parentAdcode: '140000',
        adcode: '140900',
        name: '忻州市',
        p_name: '山西省',
        label: '忻州市',
        value: '忻州市',
      },
      {
        parentAdcode: '140000',
        adcode: '141000',
        name: '临汾市',
        p_name: '山西省',
        label: '临汾市',
        value: '临汾市',
      },
      {
        parentAdcode: '140000',
        adcode: '141100',
        name: '吕梁市',
        p_name: '山西省',
        label: '吕梁市',
        value: '吕梁市',
      },
    ],
    label: '山西省',
    value: '山西省',
  },
  {
    adcode: '150000',
    name: '内蒙古自治区',
    children: [
      {
        parentAdcode: '150000',
        adcode: '150100',
        name: '呼和浩特市',
        p_name: '内蒙古自治区',
        label: '呼和浩特市',
        value: '呼和浩特市',
      },
      {
        parentAdcode: '150000',
        adcode: '150200',
        name: '包头市',
        p_name: '内蒙古自治区',
        label: '包头市',
        value: '包头市',
      },
      {
        parentAdcode: '150000',
        adcode: '150300',
        name: '乌海市',
        p_name: '内蒙古自治区',
        label: '乌海市',
        value: '乌海市',
      },
      {
        parentAdcode: '150000',
        adcode: '150400',
        name: '赤峰市',
        p_name: '内蒙古自治区',
        label: '赤峰市',
        value: '赤峰市',
      },
      {
        parentAdcode: '150000',
        adcode: '150500',
        name: '通辽市',
        p_name: '内蒙古自治区',
        label: '通辽市',
        value: '通辽市',
      },
      {
        parentAdcode: '150000',
        adcode: '150600',
        name: '鄂尔多斯市',
        p_name: '内蒙古自治区',
        label: '鄂尔多斯市',
        value: '鄂尔多斯市',
      },
      {
        parentAdcode: '150000',
        adcode: '150700',
        name: '呼伦贝尔市',
        p_name: '内蒙古自治区',
        label: '呼伦贝尔市',
        value: '呼伦贝尔市',
      },
      {
        parentAdcode: '150000',
        adcode: '150800',
        name: '巴彦淖尔市',
        p_name: '内蒙古自治区',
        label: '巴彦淖尔市',
        value: '巴彦淖尔市',
      },
      {
        parentAdcode: '150000',
        adcode: '150900',
        name: '乌兰察布市',
        p_name: '内蒙古自治区',
        label: '乌兰察布市',
        value: '乌兰察布市',
      },
      {
        parentAdcode: '150000',
        adcode: '152200',
        name: '兴安盟',
        p_name: '内蒙古自治区',
        label: '兴安盟',
        value: '兴安盟',
      },
      {
        parentAdcode: '150000',
        adcode: '152500',
        name: '锡林郭勒盟',
        p_name: '内蒙古自治区',
        label: '锡林郭勒盟',
        value: '锡林郭勒盟',
      },
      {
        parentAdcode: '150000',
        adcode: '152900',
        name: '阿拉善盟',
        p_name: '内蒙古自治区',
        label: '阿拉善盟',
        value: '阿拉善盟',
      },
    ],
    label: '内蒙古自治区',
    value: '内蒙古自治区',
  },
  {
    adcode: '210000',
    name: '辽宁省',
    children: [
      {
        parentAdcode: '210000',
        adcode: '210100',
        name: '沈阳市',
        p_name: '辽宁省',
        label: '沈阳市',
        value: '沈阳市',
      },
      {
        parentAdcode: '210000',
        adcode: '210200',
        name: '大连市',
        p_name: '辽宁省',
        label: '大连市',
        value: '大连市',
      },
      {
        parentAdcode: '210000',
        adcode: '210300',
        name: '鞍山市',
        p_name: '辽宁省',
        label: '鞍山市',
        value: '鞍山市',
      },
      {
        parentAdcode: '210000',
        adcode: '210400',
        name: '抚顺市',
        p_name: '辽宁省',
        label: '抚顺市',
        value: '抚顺市',
      },
      {
        parentAdcode: '210000',
        adcode: '210500',
        name: '本溪市',
        p_name: '辽宁省',
        label: '本溪市',
        value: '本溪市',
      },
      {
        parentAdcode: '210000',
        adcode: '210600',
        name: '丹东市',
        p_name: '辽宁省',
        label: '丹东市',
        value: '丹东市',
      },
      {
        parentAdcode: '210000',
        adcode: '210700',
        name: '锦州市',
        p_name: '辽宁省',
        label: '锦州市',
        value: '锦州市',
      },
      {
        parentAdcode: '210000',
        adcode: '210800',
        name: '营口市',
        p_name: '辽宁省',
        label: '营口市',
        value: '营口市',
      },
      {
        parentAdcode: '210000',
        adcode: '210900',
        name: '阜新市',
        p_name: '辽宁省',
        label: '阜新市',
        value: '阜新市',
      },
      {
        parentAdcode: '210000',
        adcode: '211000',
        name: '辽阳市',
        p_name: '辽宁省',
        label: '辽阳市',
        value: '辽阳市',
      },
      {
        parentAdcode: '210000',
        adcode: '211100',
        name: '盘锦市',
        p_name: '辽宁省',
        label: '盘锦市',
        value: '盘锦市',
      },
      {
        parentAdcode: '210000',
        adcode: '211200',
        name: '铁岭市',
        p_name: '辽宁省',
        label: '铁岭市',
        value: '铁岭市',
      },
      {
        parentAdcode: '210000',
        adcode: '211300',
        name: '朝阳市',
        p_name: '辽宁省',
        label: '朝阳市',
        value: '朝阳市',
      },
      {
        parentAdcode: '210000',
        adcode: '211400',
        name: '葫芦岛市',
        p_name: '辽宁省',
        label: '葫芦岛市',
        value: '葫芦岛市',
      },
    ],
    label: '辽宁省',
    value: '辽宁省',
  },
  {
    adcode: '220000',
    name: '吉林省',
    children: [
      {
        parentAdcode: '220000',
        adcode: '220100',
        name: '长春市',
        p_name: '吉林省',
        label: '长春市',
        value: '长春市',
      },
      {
        parentAdcode: '220000',
        adcode: '220200',
        name: '吉林市',
        p_name: '吉林省',
        label: '吉林市',
        value: '吉林市',
      },
      {
        parentAdcode: '220000',
        adcode: '220300',
        name: '四平市',
        p_name: '吉林省',
        label: '四平市',
        value: '四平市',
      },
      {
        parentAdcode: '220000',
        adcode: '220400',
        name: '辽源市',
        p_name: '吉林省',
        label: '辽源市',
        value: '辽源市',
      },
      {
        parentAdcode: '220000',
        adcode: '220500',
        name: '通化市',
        p_name: '吉林省',
        label: '通化市',
        value: '通化市',
      },
      {
        parentAdcode: '220000',
        adcode: '220600',
        name: '白山市',
        p_name: '吉林省',
        label: '白山市',
        value: '白山市',
      },
      {
        parentAdcode: '220000',
        adcode: '220700',
        name: '松原市',
        p_name: '吉林省',
        label: '松原市',
        value: '松原市',
      },
      {
        parentAdcode: '220000',
        adcode: '220800',
        name: '白城市',
        p_name: '吉林省',
        label: '白城市',
        value: '白城市',
      },
      {
        parentAdcode: '220000',
        adcode: '222400',
        name: '延边朝鲜族自治州',
        p_name: '吉林省',
        label: '延边朝鲜族自治州',
        value: '延边朝鲜族自治州',
      },
    ],
    label: '吉林省',
    value: '吉林省',
  },
  {
    adcode: '230000',
    name: '黑龙江省',
    children: [
      {
        parentAdcode: '230000',
        adcode: '230100',
        name: '哈尔滨市',
        p_name: '黑龙江省',
        label: '哈尔滨市',
        value: '哈尔滨市',
      },
      {
        parentAdcode: '230000',
        adcode: '230200',
        name: '齐齐哈尔市',
        p_name: '黑龙江省',
        label: '齐齐哈尔市',
        value: '齐齐哈尔市',
      },
      {
        parentAdcode: '230000',
        adcode: '230300',
        name: '鸡西市',
        p_name: '黑龙江省',
        label: '鸡西市',
        value: '鸡西市',
      },
      {
        parentAdcode: '230000',
        adcode: '230400',
        name: '鹤岗市',
        p_name: '黑龙江省',
        label: '鹤岗市',
        value: '鹤岗市',
      },
      {
        parentAdcode: '230000',
        adcode: '230500',
        name: '双鸭山市',
        p_name: '黑龙江省',
        label: '双鸭山市',
        value: '双鸭山市',
      },
      {
        parentAdcode: '230000',
        adcode: '230600',
        name: '大庆市',
        p_name: '黑龙江省',
        label: '大庆市',
        value: '大庆市',
      },
      {
        parentAdcode: '230000',
        adcode: '230700',
        name: '伊春市',
        p_name: '黑龙江省',
        label: '伊春市',
        value: '伊春市',
      },
      {
        parentAdcode: '230000',
        adcode: '230800',
        name: '佳木斯市',
        p_name: '黑龙江省',
        label: '佳木斯市',
        value: '佳木斯市',
      },
      {
        parentAdcode: '230000',
        adcode: '230900',
        name: '七台河市',
        p_name: '黑龙江省',
        label: '七台河市',
        value: '七台河市',
      },
      {
        parentAdcode: '230000',
        adcode: '231000',
        name: '牡丹江市',
        p_name: '黑龙江省',
        label: '牡丹江市',
        value: '牡丹江市',
      },
      {
        parentAdcode: '230000',
        adcode: '231100',
        name: '黑河市',
        p_name: '黑龙江省',
        label: '黑河市',
        value: '黑河市',
      },
      {
        parentAdcode: '230000',
        adcode: '231200',
        name: '绥化市',
        p_name: '黑龙江省',
        label: '绥化市',
        value: '绥化市',
      },
      {
        parentAdcode: '230000',
        adcode: '232700',
        name: '大兴安岭地区',
        p_name: '黑龙江省',
        label: '大兴安岭地区',
        value: '大兴安岭地区',
      },
    ],
    label: '黑龙江省',
    value: '黑龙江省',
  },
  {
    adcode: '310000',
    name: '上海市',
    children: [
      {
        parentAdcode: '310000',
        adcode: '310100',
        name: '上海市市辖区',
        p_name: '上海市',
        label: '上海市市辖区',
        value: '上海市市辖区',
      },
      {
        parentAdcode: '310000',
        adcode: '310200',
        name: '上海市郊县',
        p_name: '上海市',
        label: '上海市郊县',
        value: '上海市郊县',
      },
    ],
    label: '上海市',
    value: '上海市',
  },
  {
    adcode: '320000',
    name: '江苏省',
    children: [
      {
        parentAdcode: '320000',
        adcode: '320100',
        name: '南京市',
        p_name: '江苏省',
        label: '南京市',
        value: '南京市',
      },
      {
        parentAdcode: '320000',
        adcode: '320200',
        name: '无锡市',
        p_name: '江苏省',
        label: '无锡市',
        value: '无锡市',
      },
      {
        parentAdcode: '320000',
        adcode: '320300',
        name: '徐州市',
        p_name: '江苏省',
        label: '徐州市',
        value: '徐州市',
      },
      {
        parentAdcode: '320000',
        adcode: '320400',
        name: '常州市',
        p_name: '江苏省',
        label: '常州市',
        value: '常州市',
      },
      {
        parentAdcode: '320000',
        adcode: '320500',
        name: '苏州市',
        p_name: '江苏省',
        label: '苏州市',
        value: '苏州市',
      },
      {
        parentAdcode: '320000',
        adcode: '320600',
        name: '南通市',
        p_name: '江苏省',
        label: '南通市',
        value: '南通市',
      },
      {
        parentAdcode: '320000',
        adcode: '320700',
        name: '连云港市',
        p_name: '江苏省',
        label: '连云港市',
        value: '连云港市',
      },
      {
        parentAdcode: '320000',
        adcode: '320800',
        name: '淮安市',
        p_name: '江苏省',
        label: '淮安市',
        value: '淮安市',
      },
      {
        parentAdcode: '320000',
        adcode: '320900',
        name: '盐城市',
        p_name: '江苏省',
        label: '盐城市',
        value: '盐城市',
      },
      {
        parentAdcode: '320000',
        adcode: '321000',
        name: '扬州市',
        p_name: '江苏省',
        label: '扬州市',
        value: '扬州市',
      },
      {
        parentAdcode: '320000',
        adcode: '321100',
        name: '镇江市',
        p_name: '江苏省',
        label: '镇江市',
        value: '镇江市',
      },
      {
        parentAdcode: '320000',
        adcode: '321200',
        name: '泰州市',
        p_name: '江苏省',
        label: '泰州市',
        value: '泰州市',
      },
      {
        parentAdcode: '320000',
        adcode: '321300',
        name: '宿迁市',
        p_name: '江苏省',
        label: '宿迁市',
        value: '宿迁市',
      },
    ],
    label: '江苏省',
    value: '江苏省',
  },
  {
    adcode: '330000',
    name: '浙江省',
    children: [
      {
        parentAdcode: '330000',
        adcode: '330100',
        name: '杭州市',
        p_name: '浙江省',
        label: '杭州市',
        value: '杭州市',
      },
      {
        parentAdcode: '330000',
        adcode: '330200',
        name: '宁波市',
        p_name: '浙江省',
        label: '宁波市',
        value: '宁波市',
      },
      {
        parentAdcode: '330000',
        adcode: '330300',
        name: '温州市',
        p_name: '浙江省',
        label: '温州市',
        value: '温州市',
      },
      {
        parentAdcode: '330000',
        adcode: '330400',
        name: '嘉兴市',
        p_name: '浙江省',
        label: '嘉兴市',
        value: '嘉兴市',
      },
      {
        parentAdcode: '330000',
        adcode: '330500',
        name: '湖州市',
        p_name: '浙江省',
        label: '湖州市',
        value: '湖州市',
      },
      {
        parentAdcode: '330000',
        adcode: '330600',
        name: '绍兴市',
        p_name: '浙江省',
        label: '绍兴市',
        value: '绍兴市',
      },
      {
        parentAdcode: '330000',
        adcode: '330700',
        name: '金华市',
        p_name: '浙江省',
        label: '金华市',
        value: '金华市',
      },
      {
        parentAdcode: '330000',
        adcode: '330800',
        name: '衢州市',
        p_name: '浙江省',
        label: '衢州市',
        value: '衢州市',
      },
      {
        parentAdcode: '330000',
        adcode: '330900',
        name: '舟山市',
        p_name: '浙江省',
        label: '舟山市',
        value: '舟山市',
      },
      {
        parentAdcode: '330000',
        adcode: '331000',
        name: '台州市',
        p_name: '浙江省',
        label: '台州市',
        value: '台州市',
      },
      {
        parentAdcode: '330000',
        adcode: '331100',
        name: '丽水市',
        p_name: '浙江省',
        label: '丽水市',
        value: '丽水市',
      },
    ],
    label: '浙江省',
    value: '浙江省',
  },
  {
    adcode: '340000',
    name: '安徽省',
    children: [
      {
        parentAdcode: '340000',
        adcode: '340100',
        name: '合肥市',
        p_name: '安徽省',
        label: '合肥市',
        value: '合肥市',
      },
      {
        parentAdcode: '340000',
        adcode: '340200',
        name: '芜湖市',
        p_name: '安徽省',
        label: '芜湖市',
        value: '芜湖市',
      },
      {
        parentAdcode: '340000',
        adcode: '340300',
        name: '蚌埠市',
        p_name: '安徽省',
        label: '蚌埠市',
        value: '蚌埠市',
      },
      {
        parentAdcode: '340000',
        adcode: '340400',
        name: '淮南市',
        p_name: '安徽省',
        label: '淮南市',
        value: '淮南市',
      },
      {
        parentAdcode: '340000',
        adcode: '340500',
        name: '马鞍山市',
        p_name: '安徽省',
        label: '马鞍山市',
        value: '马鞍山市',
      },
      {
        parentAdcode: '340000',
        adcode: '340600',
        name: '淮北市',
        p_name: '安徽省',
        label: '淮北市',
        value: '淮北市',
      },
      {
        parentAdcode: '340000',
        adcode: '340700',
        name: '铜陵市',
        p_name: '安徽省',
        label: '铜陵市',
        value: '铜陵市',
      },
      {
        parentAdcode: '340000',
        adcode: '340800',
        name: '安庆市',
        p_name: '安徽省',
        label: '安庆市',
        value: '安庆市',
      },
      {
        parentAdcode: '340000',
        adcode: '341000',
        name: '黄山市',
        p_name: '安徽省',
        label: '黄山市',
        value: '黄山市',
      },
      {
        parentAdcode: '340000',
        adcode: '341100',
        name: '滁州市',
        p_name: '安徽省',
        label: '滁州市',
        value: '滁州市',
      },
      {
        parentAdcode: '340000',
        adcode: '341200',
        name: '阜阳市',
        p_name: '安徽省',
        label: '阜阳市',
        value: '阜阳市',
      },
      {
        parentAdcode: '340000',
        adcode: '341300',
        name: '宿州市',
        p_name: '安徽省',
        label: '宿州市',
        value: '宿州市',
      },
      {
        parentAdcode: '340000',
        adcode: '341500',
        name: '六安市',
        p_name: '安徽省',
        label: '六安市',
        value: '六安市',
      },
      {
        parentAdcode: '340000',
        adcode: '341600',
        name: '亳州市',
        p_name: '安徽省',
        label: '亳州市',
        value: '亳州市',
      },
      {
        parentAdcode: '340000',
        adcode: '341700',
        name: '池州市',
        p_name: '安徽省',
        label: '池州市',
        value: '池州市',
      },
      {
        parentAdcode: '340000',
        adcode: '341800',
        name: '宣城市',
        p_name: '安徽省',
        label: '宣城市',
        value: '宣城市',
      },
    ],
    label: '安徽省',
    value: '安徽省',
  },
  {
    adcode: '350000',
    name: '福建省',
    children: [
      {
        parentAdcode: '350000',
        adcode: '350100',
        name: '福州市',
        p_name: '福建省',
        label: '福州市',
        value: '福州市',
      },
      {
        parentAdcode: '350000',
        adcode: '350200',
        name: '厦门市',
        p_name: '福建省',
        label: '厦门市',
        value: '厦门市',
      },
      {
        parentAdcode: '350000',
        adcode: '350300',
        name: '莆田市',
        p_name: '福建省',
        label: '莆田市',
        value: '莆田市',
      },
      {
        parentAdcode: '350000',
        adcode: '350400',
        name: '三明市',
        p_name: '福建省',
        label: '三明市',
        value: '三明市',
      },
      {
        parentAdcode: '350000',
        adcode: '350500',
        name: '泉州市',
        p_name: '福建省',
        label: '泉州市',
        value: '泉州市',
      },
      {
        parentAdcode: '350000',
        adcode: '350600',
        name: '漳州市',
        p_name: '福建省',
        label: '漳州市',
        value: '漳州市',
      },
      {
        parentAdcode: '350000',
        adcode: '350700',
        name: '南平市',
        p_name: '福建省',
        label: '南平市',
        value: '南平市',
      },
      {
        parentAdcode: '350000',
        adcode: '350800',
        name: '龙岩市',
        p_name: '福建省',
        label: '龙岩市',
        value: '龙岩市',
      },
      {
        parentAdcode: '350000',
        adcode: '350900',
        name: '宁德市',
        p_name: '福建省',
        label: '宁德市',
        value: '宁德市',
      },
    ],
    label: '福建省',
    value: '福建省',
  },
  {
    adcode: '360000',
    name: '江西省',
    children: [
      {
        parentAdcode: '360000',
        adcode: '360100',
        name: '南昌市',
        p_name: '江西省',
        label: '南昌市',
        value: '南昌市',
      },
      {
        parentAdcode: '360000',
        adcode: '360200',
        name: '景德镇市',
        p_name: '江西省',
        label: '景德镇市',
        value: '景德镇市',
      },
      {
        parentAdcode: '360000',
        adcode: '360300',
        name: '萍乡市',
        p_name: '江西省',
        label: '萍乡市',
        value: '萍乡市',
      },
      {
        parentAdcode: '360000',
        adcode: '360400',
        name: '九江市',
        p_name: '江西省',
        label: '九江市',
        value: '九江市',
      },
      {
        parentAdcode: '360000',
        adcode: '360500',
        name: '新余市',
        p_name: '江西省',
        label: '新余市',
        value: '新余市',
      },
      {
        parentAdcode: '360000',
        adcode: '360600',
        name: '鹰潭市',
        p_name: '江西省',
        label: '鹰潭市',
        value: '鹰潭市',
      },
      {
        parentAdcode: '360000',
        adcode: '360700',
        name: '赣州市',
        p_name: '江西省',
        label: '赣州市',
        value: '赣州市',
      },
      {
        parentAdcode: '360000',
        adcode: '360800',
        name: '吉安市',
        p_name: '江西省',
        label: '吉安市',
        value: '吉安市',
      },
      {
        parentAdcode: '360000',
        adcode: '360900',
        name: '宜春市',
        p_name: '江西省',
        label: '宜春市',
        value: '宜春市',
      },
      {
        parentAdcode: '360000',
        adcode: '361000',
        name: '抚州市',
        p_name: '江西省',
        label: '抚州市',
        value: '抚州市',
      },
      {
        parentAdcode: '360000',
        adcode: '361100',
        name: '上饶市',
        p_name: '江西省',
        label: '上饶市',
        value: '上饶市',
      },
    ],
    label: '江西省',
    value: '江西省',
  },
  {
    adcode: '370000',
    name: '山东省',
    children: [
      {
        parentAdcode: '370000',
        adcode: '370100',
        name: '济南市',
        p_name: '山东省',
        label: '济南市',
        value: '济南市',
      },
      {
        parentAdcode: '370000',
        adcode: '370200',
        name: '青岛市',
        p_name: '山东省',
        label: '青岛市',
        value: '青岛市',
      },
      {
        parentAdcode: '370000',
        adcode: '370300',
        name: '淄博市',
        p_name: '山东省',
        label: '淄博市',
        value: '淄博市',
      },
      {
        parentAdcode: '370000',
        adcode: '370400',
        name: '枣庄市',
        p_name: '山东省',
        label: '枣庄市',
        value: '枣庄市',
      },
      {
        parentAdcode: '370000',
        adcode: '370500',
        name: '东营市',
        p_name: '山东省',
        label: '东营市',
        value: '东营市',
      },
      {
        parentAdcode: '370000',
        adcode: '370600',
        name: '烟台市',
        p_name: '山东省',
        label: '烟台市',
        value: '烟台市',
      },
      {
        parentAdcode: '370000',
        adcode: '370700',
        name: '潍坊市',
        p_name: '山东省',
        label: '潍坊市',
        value: '潍坊市',
      },
      {
        parentAdcode: '370000',
        adcode: '370800',
        name: '济宁市',
        p_name: '山东省',
        label: '济宁市',
        value: '济宁市',
      },
      {
        parentAdcode: '370000',
        adcode: '370900',
        name: '泰安市',
        p_name: '山东省',
        label: '泰安市',
        value: '泰安市',
      },
      {
        parentAdcode: '370000',
        adcode: '371000',
        name: '威海市',
        p_name: '山东省',
        label: '威海市',
        value: '威海市',
      },
      {
        parentAdcode: '370000',
        adcode: '371100',
        name: '日照市',
        p_name: '山东省',
        label: '日照市',
        value: '日照市',
      },
      {
        parentAdcode: '370000',
        adcode: '371200',
        name: '莱芜市',
        p_name: '山东省',
        label: '莱芜市',
        value: '莱芜市',
      },
      {
        parentAdcode: '370000',
        adcode: '371300',
        name: '临沂市',
        p_name: '山东省',
        label: '临沂市',
        value: '临沂市',
      },
      {
        parentAdcode: '370000',
        adcode: '371400',
        name: '德州市',
        p_name: '山东省',
        label: '德州市',
        value: '德州市',
      },
      {
        parentAdcode: '370000',
        adcode: '371500',
        name: '聊城市',
        p_name: '山东省',
        label: '聊城市',
        value: '聊城市',
      },
      {
        parentAdcode: '370000',
        adcode: '371600',
        name: '滨州市',
        p_name: '山东省',
        label: '滨州市',
        value: '滨州市',
      },
      {
        parentAdcode: '370000',
        adcode: '371700',
        name: '菏泽市',
        p_name: '山东省',
        label: '菏泽市',
        value: '菏泽市',
      },
    ],
    label: '山东省',
    value: '山东省',
  },
  {
    adcode: '410000',
    name: '河南省',
    children: [
      {
        parentAdcode: '410000',
        adcode: '410100',
        name: '郑州市',
        p_name: '河南省',
        label: '郑州市',
        value: '郑州市',
      },
      {
        parentAdcode: '410000',
        adcode: '410200',
        name: '开封市',
        p_name: '河南省',
        label: '开封市',
        value: '开封市',
      },
      {
        parentAdcode: '410000',
        adcode: '410300',
        name: '洛阳市',
        p_name: '河南省',
        label: '洛阳市',
        value: '洛阳市',
      },
      {
        parentAdcode: '410000',
        adcode: '410400',
        name: '平顶山市',
        p_name: '河南省',
        label: '平顶山市',
        value: '平顶山市',
      },
      {
        parentAdcode: '410000',
        adcode: '410500',
        name: '安阳市',
        p_name: '河南省',
        label: '安阳市',
        value: '安阳市',
      },
      {
        parentAdcode: '410000',
        adcode: '410600',
        name: '鹤壁市',
        p_name: '河南省',
        label: '鹤壁市',
        value: '鹤壁市',
      },
      {
        parentAdcode: '410000',
        adcode: '410700',
        name: '新乡市',
        p_name: '河南省',
        label: '新乡市',
        value: '新乡市',
      },
      {
        parentAdcode: '410000',
        adcode: '410800',
        name: '焦作市',
        p_name: '河南省',
        label: '焦作市',
        value: '焦作市',
      },
      {
        parentAdcode: '410000',
        adcode: '410900',
        name: '濮阳市',
        p_name: '河南省',
        label: '濮阳市',
        value: '濮阳市',
      },
      {
        parentAdcode: '410000',
        adcode: '411000',
        name: '许昌市',
        p_name: '河南省',
        label: '许昌市',
        value: '许昌市',
      },
      {
        parentAdcode: '410000',
        adcode: '411100',
        name: '漯河市',
        p_name: '河南省',
        label: '漯河市',
        value: '漯河市',
      },
      {
        parentAdcode: '410000',
        adcode: '411200',
        name: '三门峡市',
        p_name: '河南省',
        label: '三门峡市',
        value: '三门峡市',
      },
      {
        parentAdcode: '410000',
        adcode: '411300',
        name: '南阳市',
        p_name: '河南省',
        label: '南阳市',
        value: '南阳市',
      },
      {
        parentAdcode: '410000',
        adcode: '411400',
        name: '商丘市',
        p_name: '河南省',
        label: '商丘市',
        value: '商丘市',
      },
      {
        parentAdcode: '410000',
        adcode: '411500',
        name: '信阳市',
        p_name: '河南省',
        label: '信阳市',
        value: '信阳市',
      },
      {
        parentAdcode: '410000',
        adcode: '411600',
        name: '周口市',
        p_name: '河南省',
        label: '周口市',
        value: '周口市',
      },
      {
        parentAdcode: '410000',
        adcode: '411700',
        name: '驻马店市',
        p_name: '河南省',
        label: '驻马店市',
        value: '驻马店市',
      },
      {
        parentAdcode: '410000',
        adcode: '419001',
        name: '济源市',
        p_name: '河南省',
        label: '济源市',
        value: '济源市',
      },
    ],
    label: '河南省',
    value: '河南省',
  },
  {
    adcode: '420000',
    name: '湖北省',
    children: [
      {
        parentAdcode: '420000',
        adcode: '420100',
        name: '武汉市',
        p_name: '湖北省',
        label: '武汉市',
        value: '武汉市',
      },
      {
        parentAdcode: '420000',
        adcode: '420200',
        name: '黄石市',
        p_name: '湖北省',
        label: '黄石市',
        value: '黄石市',
      },
      {
        parentAdcode: '420000',
        adcode: '420300',
        name: '十堰市',
        p_name: '湖北省',
        label: '十堰市',
        value: '十堰市',
      },
      {
        parentAdcode: '420000',
        adcode: '420500',
        name: '宜昌市',
        p_name: '湖北省',
        label: '宜昌市',
        value: '宜昌市',
      },
      {
        parentAdcode: '420000',
        adcode: '420600',
        name: '襄阳市',
        p_name: '湖北省',
        label: '襄阳市',
        value: '襄阳市',
      },
      {
        parentAdcode: '420000',
        adcode: '420700',
        name: '鄂州市',
        p_name: '湖北省',
        label: '鄂州市',
        value: '鄂州市',
      },
      {
        parentAdcode: '420000',
        adcode: '420800',
        name: '荆门市',
        p_name: '湖北省',
        label: '荆门市',
        value: '荆门市',
      },
      {
        parentAdcode: '420000',
        adcode: '420900',
        name: '孝感市',
        p_name: '湖北省',
        label: '孝感市',
        value: '孝感市',
      },
      {
        parentAdcode: '420000',
        adcode: '421000',
        name: '荆州市',
        p_name: '湖北省',
        label: '荆州市',
        value: '荆州市',
      },
      {
        parentAdcode: '420000',
        adcode: '421100',
        name: '黄冈市',
        p_name: '湖北省',
        label: '黄冈市',
        value: '黄冈市',
      },
      {
        parentAdcode: '420000',
        adcode: '421200',
        name: '咸宁市',
        p_name: '湖北省',
        label: '咸宁市',
        value: '咸宁市',
      },
      {
        parentAdcode: '420000',
        adcode: '421300',
        name: '随州市',
        p_name: '湖北省',
        label: '随州市',
        value: '随州市',
      },
      {
        parentAdcode: '420000',
        adcode: '422800',
        name: '恩施土家族苗族自治州',
        p_name: '湖北省',
        label: '恩施土家族苗族自治州',
        value: '恩施土家族苗族自治州',
      },
      {
        parentAdcode: '420000',
        adcode: '429004',
        name: '仙桃市',
        p_name: '湖北省',
        label: '仙桃市',
        value: '仙桃市',
      },
      {
        parentAdcode: '420000',
        adcode: '429005',
        name: '潜江市',
        p_name: '湖北省',
        label: '潜江市',
        value: '潜江市',
      },
      {
        parentAdcode: '420000',
        adcode: '429006',
        name: '天门市',
        p_name: '湖北省',
        label: '天门市',
        value: '天门市',
      },
      {
        parentAdcode: '420000',
        adcode: '429021',
        name: '神农架林区',
        p_name: '湖北省',
        label: '神农架林区',
        value: '神农架林区',
      },
    ],
    label: '湖北省',
    value: '湖北省',
  },
  {
    adcode: '430000',
    name: '湖南省',
    children: [
      {
        parentAdcode: '430000',
        adcode: '430100',
        name: '长沙市',
        p_name: '湖南省',
        label: '长沙市',
        value: '长沙市',
      },
      {
        parentAdcode: '430000',
        adcode: '430200',
        name: '株洲市',
        p_name: '湖南省',
        label: '株洲市',
        value: '株洲市',
      },
      {
        parentAdcode: '430000',
        adcode: '430300',
        name: '湘潭市',
        p_name: '湖南省',
        label: '湘潭市',
        value: '湘潭市',
      },
      {
        parentAdcode: '430000',
        adcode: '430400',
        name: '衡阳市',
        p_name: '湖南省',
        label: '衡阳市',
        value: '衡阳市',
      },
      {
        parentAdcode: '430000',
        adcode: '430500',
        name: '邵阳市',
        p_name: '湖南省',
        label: '邵阳市',
        value: '邵阳市',
      },
      {
        parentAdcode: '430000',
        adcode: '430600',
        name: '岳阳市',
        p_name: '湖南省',
        label: '岳阳市',
        value: '岳阳市',
      },
      {
        parentAdcode: '430000',
        adcode: '430700',
        name: '常德市',
        p_name: '湖南省',
        label: '常德市',
        value: '常德市',
      },
      {
        parentAdcode: '430000',
        adcode: '430800',
        name: '张家界市',
        p_name: '湖南省',
        label: '张家界市',
        value: '张家界市',
      },
      {
        parentAdcode: '430000',
        adcode: '430900',
        name: '益阳市',
        p_name: '湖南省',
        label: '益阳市',
        value: '益阳市',
      },
      {
        parentAdcode: '430000',
        adcode: '431000',
        name: '郴州市',
        p_name: '湖南省',
        label: '郴州市',
        value: '郴州市',
      },
      {
        parentAdcode: '430000',
        adcode: '431100',
        name: '永州市',
        p_name: '湖南省',
        label: '永州市',
        value: '永州市',
      },
      {
        parentAdcode: '430000',
        adcode: '431200',
        name: '怀化市',
        p_name: '湖南省',
        label: '怀化市',
        value: '怀化市',
      },
      {
        parentAdcode: '430000',
        adcode: '431300',
        name: '娄底市',
        p_name: '湖南省',
        label: '娄底市',
        value: '娄底市',
      },
      {
        parentAdcode: '430000',
        adcode: '433100',
        name: '湘西土家族苗族自治州',
        p_name: '湖南省',
        label: '湘西土家族苗族自治州',
        value: '湘西土家族苗族自治州',
      },
    ],
    label: '湖南省',
    value: '湖南省',
  },
  {
    adcode: '440000',
    name: '广东省',
    children: [
      {
        parentAdcode: '440000',
        adcode: '440100',
        name: '广州市',
        p_name: '广东省',
        label: '广州市',
        value: '广州市',
      },
      {
        parentAdcode: '440000',
        adcode: '440200',
        name: '韶关市',
        p_name: '广东省',
        label: '韶关市',
        value: '韶关市',
      },
      {
        parentAdcode: '440000',
        adcode: '440300',
        name: '深圳市',
        p_name: '广东省',
        label: '深圳市',
        value: '深圳市',
      },
      {
        parentAdcode: '440000',
        adcode: '440400',
        name: '珠海市',
        p_name: '广东省',
        label: '珠海市',
        value: '珠海市',
      },
      {
        parentAdcode: '440000',
        adcode: '440500',
        name: '汕头市',
        p_name: '广东省',
        label: '汕头市',
        value: '汕头市',
      },
      {
        parentAdcode: '440000',
        adcode: '440600',
        name: '佛山市',
        p_name: '广东省',
        label: '佛山市',
        value: '佛山市',
      },
      {
        parentAdcode: '440000',
        adcode: '440700',
        name: '江门市',
        p_name: '广东省',
        label: '江门市',
        value: '江门市',
      },
      {
        parentAdcode: '440000',
        adcode: '440800',
        name: '湛江市',
        p_name: '广东省',
        label: '湛江市',
        value: '湛江市',
      },
      {
        parentAdcode: '440000',
        adcode: '440900',
        name: '茂名市',
        p_name: '广东省',
        label: '茂名市',
        value: '茂名市',
      },
      {
        parentAdcode: '440000',
        adcode: '441200',
        name: '肇庆市',
        p_name: '广东省',
        label: '肇庆市',
        value: '肇庆市',
      },
      {
        parentAdcode: '440000',
        adcode: '441300',
        name: '惠州市',
        p_name: '广东省',
        label: '惠州市',
        value: '惠州市',
      },
      {
        parentAdcode: '440000',
        adcode: '441400',
        name: '梅州市',
        p_name: '广东省',
        label: '梅州市',
        value: '梅州市',
      },
      {
        parentAdcode: '440000',
        adcode: '441500',
        name: '汕尾市',
        p_name: '广东省',
        label: '汕尾市',
        value: '汕尾市',
      },
      {
        parentAdcode: '440000',
        adcode: '441600',
        name: '河源市',
        p_name: '广东省',
        label: '河源市',
        value: '河源市',
      },
      {
        parentAdcode: '440000',
        adcode: '441700',
        name: '阳江市',
        p_name: '广东省',
        label: '阳江市',
        value: '阳江市',
      },
      {
        parentAdcode: '440000',
        adcode: '441800',
        name: '清远市',
        p_name: '广东省',
        label: '清远市',
        value: '清远市',
      },
      {
        parentAdcode: '440000',
        adcode: '441900',
        name: '东莞市',
        p_name: '广东省',
        label: '东莞市',
        value: '东莞市',
      },
      {
        parentAdcode: '440000',
        adcode: '442000',
        name: '中山市',
        p_name: '广东省',
        label: '中山市',
        value: '中山市',
      },
      {
        parentAdcode: '440000',
        adcode: '445100',
        name: '潮州市',
        p_name: '广东省',
        label: '潮州市',
        value: '潮州市',
      },
      {
        parentAdcode: '440000',
        adcode: '445200',
        name: '揭阳市',
        p_name: '广东省',
        label: '揭阳市',
        value: '揭阳市',
      },
      {
        parentAdcode: '440000',
        adcode: '445300',
        name: '云浮市',
        p_name: '广东省',
        label: '云浮市',
        value: '云浮市',
      },
    ],
    label: '广东省',
    value: '广东省',
  },
  {
    adcode: '450000',
    name: '广西壮族自治区',
    children: [
      {
        parentAdcode: '450000',
        adcode: '450100',
        name: '南宁市',
        p_name: '广西壮族自治区',
        label: '南宁市',
        value: '南宁市',
      },
      {
        parentAdcode: '450000',
        adcode: '450200',
        name: '柳州市',
        p_name: '广西壮族自治区',
        label: '柳州市',
        value: '柳州市',
      },
      {
        parentAdcode: '450000',
        adcode: '450300',
        name: '桂林市',
        p_name: '广西壮族自治区',
        label: '桂林市',
        value: '桂林市',
      },
      {
        parentAdcode: '450000',
        adcode: '450400',
        name: '梧州市',
        p_name: '广西壮族自治区',
        label: '梧州市',
        value: '梧州市',
      },
      {
        parentAdcode: '450000',
        adcode: '450500',
        name: '北海市',
        p_name: '广西壮族自治区',
        label: '北海市',
        value: '北海市',
      },
      {
        parentAdcode: '450000',
        adcode: '450600',
        name: '防城港市',
        p_name: '广西壮族自治区',
        label: '防城港市',
        value: '防城港市',
      },
      {
        parentAdcode: '450000',
        adcode: '450700',
        name: '钦州市',
        p_name: '广西壮族自治区',
        label: '钦州市',
        value: '钦州市',
      },
      {
        parentAdcode: '450000',
        adcode: '450800',
        name: '贵港市',
        p_name: '广西壮族自治区',
        label: '贵港市',
        value: '贵港市',
      },
      {
        parentAdcode: '450000',
        adcode: '450900',
        name: '玉林市',
        p_name: '广西壮族自治区',
        label: '玉林市',
        value: '玉林市',
      },
      {
        parentAdcode: '450000',
        adcode: '451000',
        name: '百色市',
        p_name: '广西壮族自治区',
        label: '百色市',
        value: '百色市',
      },
      {
        parentAdcode: '450000',
        adcode: '451100',
        name: '贺州市',
        p_name: '广西壮族自治区',
        label: '贺州市',
        value: '贺州市',
      },
      {
        parentAdcode: '450000',
        adcode: '451200',
        name: '河池市',
        p_name: '广西壮族自治区',
        label: '河池市',
        value: '河池市',
      },
      {
        parentAdcode: '450000',
        adcode: '451300',
        name: '来宾市',
        p_name: '广西壮族自治区',
        label: '来宾市',
        value: '来宾市',
      },
      {
        parentAdcode: '450000',
        adcode: '451400',
        name: '崇左市',
        p_name: '广西壮族自治区',
        label: '崇左市',
        value: '崇左市',
      },
    ],
    label: '广西壮族自治区',
    value: '广西壮族自治区',
  },
  {
    adcode: '460000',
    name: '海南省',
    children: [
      {
        parentAdcode: '460000',
        adcode: '460100',
        name: '海口市',
        p_name: '海南省',
        label: '海口市',
        value: '海口市',
      },
      {
        parentAdcode: '460000',
        adcode: '460200',
        name: '三亚市',
        p_name: '海南省',
        label: '三亚市',
        value: '三亚市',
      },
      {
        parentAdcode: '460000',
        adcode: '460300',
        name: '三沙市',
        p_name: '海南省',
        label: '三沙市',
        value: '三沙市',
      },
      {
        parentAdcode: '460000',
        adcode: '460400',
        name: '儋州市',
        p_name: '海南省',
        label: '儋州市',
        value: '儋州市',
      },
      {
        parentAdcode: '460000',
        adcode: '469001',
        name: '五指山市',
        p_name: '海南省',
        label: '五指山市',
        value: '五指山市',
      },
      {
        parentAdcode: '460000',
        adcode: '469002',
        name: '琼海市',
        p_name: '海南省',
        label: '琼海市',
        value: '琼海市',
      },
      {
        parentAdcode: '460000',
        adcode: '469005',
        name: '文昌市',
        p_name: '海南省',
        label: '文昌市',
        value: '文昌市',
      },
      {
        parentAdcode: '460000',
        adcode: '469006',
        name: '万宁市',
        p_name: '海南省',
        label: '万宁市',
        value: '万宁市',
      },
      {
        parentAdcode: '460000',
        adcode: '469007',
        name: '东方市',
        p_name: '海南省',
        label: '东方市',
        value: '东方市',
      },
      {
        parentAdcode: '460000',
        adcode: '469021',
        name: '定安县',
        p_name: '海南省',
        label: '定安县',
        value: '定安县',
      },
      {
        parentAdcode: '460000',
        adcode: '469022',
        name: '屯昌县',
        p_name: '海南省',
        label: '屯昌县',
        value: '屯昌县',
      },
      {
        parentAdcode: '460000',
        adcode: '469023',
        name: '澄迈县',
        p_name: '海南省',
        label: '澄迈县',
        value: '澄迈县',
      },
      {
        parentAdcode: '460000',
        adcode: '469024',
        name: '临高县',
        p_name: '海南省',
        label: '临高县',
        value: '临高县',
      },
      {
        parentAdcode: '460000',
        adcode: '469025',
        name: '白沙黎族自治县',
        p_name: '海南省',
        label: '白沙黎族自治县',
        value: '白沙黎族自治县',
      },
      {
        parentAdcode: '460000',
        adcode: '469026',
        name: '昌江黎族自治县',
        p_name: '海南省',
        label: '昌江黎族自治县',
        value: '昌江黎族自治县',
      },
      {
        parentAdcode: '460000',
        adcode: '469027',
        name: '乐东黎族自治县',
        p_name: '海南省',
        label: '乐东黎族自治县',
        value: '乐东黎族自治县',
      },
      {
        parentAdcode: '460000',
        adcode: '469028',
        name: '陵水黎族自治县',
        p_name: '海南省',
        label: '陵水黎族自治县',
        value: '陵水黎族自治县',
      },
      {
        parentAdcode: '460000',
        adcode: '469029',
        name: '保亭黎族苗族自治县',
        p_name: '海南省',
        label: '保亭黎族苗族自治县',
        value: '保亭黎族苗族自治县',
      },
      {
        parentAdcode: '460000',
        adcode: '469030',
        name: '琼中黎族苗族自治县',
        p_name: '海南省',
        label: '琼中黎族苗族自治县',
        value: '琼中黎族苗族自治县',
      },
    ],
    label: '海南省',
    value: '海南省',
  },
  {
    adcode: '500000',
    name: '重庆市',
    children: [
      {
        parentAdcode: '500000',
        adcode: '500100',
        name: '重庆市市辖区',
        p_name: '重庆市',
        label: '重庆市市辖区',
        value: '重庆市市辖区',
      },
      {
        parentAdcode: '500000',
        adcode: '500200',
        name: '重庆市郊县',
        p_name: '重庆市',
        label: '重庆市郊县',
        value: '重庆市郊县',
      },
    ],
    label: '重庆市',
    value: '重庆市',
  },
  {
    adcode: '510000',
    name: '四川省',
    children: [
      {
        parentAdcode: '510000',
        adcode: '510100',
        name: '成都市',
        p_name: '四川省',
        label: '成都市',
        value: '成都市',
      },
      {
        parentAdcode: '510000',
        adcode: '510300',
        name: '自贡市',
        p_name: '四川省',
        label: '自贡市',
        value: '自贡市',
      },
      {
        parentAdcode: '510000',
        adcode: '510400',
        name: '攀枝花市',
        p_name: '四川省',
        label: '攀枝花市',
        value: '攀枝花市',
      },
      {
        parentAdcode: '510000',
        adcode: '510500',
        name: '泸州市',
        p_name: '四川省',
        label: '泸州市',
        value: '泸州市',
      },
      {
        parentAdcode: '510000',
        adcode: '510600',
        name: '德阳市',
        p_name: '四川省',
        label: '德阳市',
        value: '德阳市',
      },
      {
        parentAdcode: '510000',
        adcode: '510700',
        name: '绵阳市',
        p_name: '四川省',
        label: '绵阳市',
        value: '绵阳市',
      },
      {
        parentAdcode: '510000',
        adcode: '510800',
        name: '广元市',
        p_name: '四川省',
        label: '广元市',
        value: '广元市',
      },
      {
        parentAdcode: '510000',
        adcode: '510900',
        name: '遂宁市',
        p_name: '四川省',
        label: '遂宁市',
        value: '遂宁市',
      },
      {
        parentAdcode: '510000',
        adcode: '511000',
        name: '内江市',
        p_name: '四川省',
        label: '内江市',
        value: '内江市',
      },
      {
        parentAdcode: '510000',
        adcode: '511100',
        name: '乐山市',
        p_name: '四川省',
        label: '乐山市',
        value: '乐山市',
      },
      {
        parentAdcode: '510000',
        adcode: '511300',
        name: '南充市',
        p_name: '四川省',
        label: '南充市',
        value: '南充市',
      },
      {
        parentAdcode: '510000',
        adcode: '511400',
        name: '眉山市',
        p_name: '四川省',
        label: '眉山市',
        value: '眉山市',
      },
      {
        parentAdcode: '510000',
        adcode: '511500',
        name: '宜宾市',
        p_name: '四川省',
        label: '宜宾市',
        value: '宜宾市',
      },
      {
        parentAdcode: '510000',
        adcode: '511600',
        name: '广安市',
        p_name: '四川省',
        label: '广安市',
        value: '广安市',
      },
      {
        parentAdcode: '510000',
        adcode: '511700',
        name: '达州市',
        p_name: '四川省',
        label: '达州市',
        value: '达州市',
      },
      {
        parentAdcode: '510000',
        adcode: '511800',
        name: '雅安市',
        p_name: '四川省',
        label: '雅安市',
        value: '雅安市',
      },
      {
        parentAdcode: '510000',
        adcode: '511900',
        name: '巴中市',
        p_name: '四川省',
        label: '巴中市',
        value: '巴中市',
      },
      {
        parentAdcode: '510000',
        adcode: '512000',
        name: '资阳市',
        p_name: '四川省',
        label: '资阳市',
        value: '资阳市',
      },
      {
        parentAdcode: '510000',
        adcode: '513200',
        name: '阿坝藏族羌族自治州',
        p_name: '四川省',
        label: '阿坝藏族羌族自治州',
        value: '阿坝藏族羌族自治州',
      },
      {
        parentAdcode: '510000',
        adcode: '513300',
        name: '甘孜藏族自治州',
        p_name: '四川省',
        label: '甘孜藏族自治州',
        value: '甘孜藏族自治州',
      },
      {
        parentAdcode: '510000',
        adcode: '513400',
        name: '凉山彝族自治州',
        p_name: '四川省',
        label: '凉山彝族自治州',
        value: '凉山彝族自治州',
      },
    ],
    label: '四川省',
    value: '四川省',
  },
  {
    adcode: '520000',
    name: '贵州省',
    children: [
      {
        parentAdcode: '520000',
        adcode: '520100',
        name: '贵阳市',
        p_name: '贵州省',
        label: '贵阳市',
        value: '贵阳市',
      },
      {
        parentAdcode: '520000',
        adcode: '520200',
        name: '六盘水市',
        p_name: '贵州省',
        label: '六盘水市',
        value: '六盘水市',
      },
      {
        parentAdcode: '520000',
        adcode: '520300',
        name: '遵义市',
        p_name: '贵州省',
        label: '遵义市',
        value: '遵义市',
      },
      {
        parentAdcode: '520000',
        adcode: '520400',
        name: '安顺市',
        p_name: '贵州省',
        label: '安顺市',
        value: '安顺市',
      },
      {
        parentAdcode: '520000',
        adcode: '520500',
        name: '毕节市',
        p_name: '贵州省',
        label: '毕节市',
        value: '毕节市',
      },
      {
        parentAdcode: '520000',
        adcode: '520600',
        name: '铜仁市',
        p_name: '贵州省',
        label: '铜仁市',
        value: '铜仁市',
      },
      {
        parentAdcode: '520000',
        adcode: '522300',
        name: '黔西南布依族苗族自治州',
        p_name: '贵州省',
        label: '黔西南布依族苗族自治州',
        value: '黔西南布依族苗族自治州',
      },
      {
        parentAdcode: '520000',
        adcode: '522600',
        name: '黔东南苗族侗族自治州',
        p_name: '贵州省',
        label: '黔东南苗族侗族自治州',
        value: '黔东南苗族侗族自治州',
      },
      {
        parentAdcode: '520000',
        adcode: '522700',
        name: '黔南布依族苗族自治州',
        p_name: '贵州省',
        label: '黔南布依族苗族自治州',
        value: '黔南布依族苗族自治州',
      },
    ],
    label: '贵州省',
    value: '贵州省',
  },
  {
    adcode: '530000',
    name: '云南省',
    children: [
      {
        parentAdcode: '530000',
        adcode: '530100',
        name: '昆明市',
        p_name: '云南省',
        label: '昆明市',
        value: '昆明市',
      },
      {
        parentAdcode: '530000',
        adcode: '530300',
        name: '曲靖市',
        p_name: '云南省',
        label: '曲靖市',
        value: '曲靖市',
      },
      {
        parentAdcode: '530000',
        adcode: '530400',
        name: '玉溪市',
        p_name: '云南省',
        label: '玉溪市',
        value: '玉溪市',
      },
      {
        parentAdcode: '530000',
        adcode: '530500',
        name: '保山市',
        p_name: '云南省',
        label: '保山市',
        value: '保山市',
      },
      {
        parentAdcode: '530000',
        adcode: '530600',
        name: '昭通市',
        p_name: '云南省',
        label: '昭通市',
        value: '昭通市',
      },
      {
        parentAdcode: '530000',
        adcode: '530700',
        name: '丽江市',
        p_name: '云南省',
        label: '丽江市',
        value: '丽江市',
      },
      {
        parentAdcode: '530000',
        adcode: '530800',
        name: '普洱市',
        p_name: '云南省',
        label: '普洱市',
        value: '普洱市',
      },
      {
        parentAdcode: '530000',
        adcode: '530900',
        name: '临沧市',
        p_name: '云南省',
        label: '临沧市',
        value: '临沧市',
      },
      {
        parentAdcode: '530000',
        adcode: '532300',
        name: '楚雄彝族自治州',
        p_name: '云南省',
        label: '楚雄彝族自治州',
        value: '楚雄彝族自治州',
      },
      {
        parentAdcode: '530000',
        adcode: '532500',
        name: '红河哈尼族彝族自治州',
        p_name: '云南省',
        label: '红河哈尼族彝族自治州',
        value: '红河哈尼族彝族自治州',
      },
      {
        parentAdcode: '530000',
        adcode: '532600',
        name: '文山壮族苗族自治州',
        p_name: '云南省',
        label: '文山壮族苗族自治州',
        value: '文山壮族苗族自治州',
      },
      {
        parentAdcode: '530000',
        adcode: '532800',
        name: '西双版纳傣族自治州',
        p_name: '云南省',
        label: '西双版纳傣族自治州',
        value: '西双版纳傣族自治州',
      },
      {
        parentAdcode: '530000',
        adcode: '532900',
        name: '大理白族自治州',
        p_name: '云南省',
        label: '大理白族自治州',
        value: '大理白族自治州',
      },
      {
        parentAdcode: '530000',
        adcode: '533100',
        name: '德宏傣族景颇族自治州',
        p_name: '云南省',
        label: '德宏傣族景颇族自治州',
        value: '德宏傣族景颇族自治州',
      },
      {
        parentAdcode: '530000',
        adcode: '533300',
        name: '怒江傈僳族自治州',
        p_name: '云南省',
        label: '怒江傈僳族自治州',
        value: '怒江傈僳族自治州',
      },
      {
        parentAdcode: '530000',
        adcode: '533400',
        name: '迪庆藏族自治州',
        p_name: '云南省',
        label: '迪庆藏族自治州',
        value: '迪庆藏族自治州',
      },
    ],
    label: '云南省',
    value: '云南省',
  },
  {
    adcode: '540000',
    name: '西藏自治区',
    children: [
      {
        parentAdcode: '540000',
        adcode: '540100',
        name: '拉萨市',
        p_name: '西藏自治区',
        label: '拉萨市',
        value: '拉萨市',
      },
      {
        parentAdcode: '540000',
        adcode: '540200',
        name: '日喀则市',
        p_name: '西藏自治区',
        label: '日喀则市',
        value: '日喀则市',
      },
      {
        parentAdcode: '540000',
        adcode: '540300',
        name: '昌都市',
        p_name: '西藏自治区',
        label: '昌都市',
        value: '昌都市',
      },
      {
        parentAdcode: '540000',
        adcode: '542200',
        name: '山南地区',
        p_name: '西藏自治区',
        label: '山南地区',
        value: '山南地区',
      },
      {
        parentAdcode: '540000',
        adcode: '542400',
        name: '那曲地区',
        p_name: '西藏自治区',
        label: '那曲地区',
        value: '那曲地区',
      },
      {
        parentAdcode: '540000',
        adcode: '542500',
        name: '阿里地区',
        p_name: '西藏自治区',
        label: '阿里地区',
        value: '阿里地区',
      },
      {
        parentAdcode: '540000',
        adcode: '540400',
        name: '林芝市',
        p_name: '西藏自治区',
        label: '林芝市',
        value: '林芝市',
      },
    ],
    label: '西藏自治区',
    value: '西藏自治区',
  },
  {
    adcode: '610000',
    name: '陕西省',
    children: [
      {
        parentAdcode: '610000',
        adcode: '610100',
        name: '西安市',
        p_name: '陕西省',
        label: '西安市',
        value: '西安市',
      },
      {
        parentAdcode: '610000',
        adcode: '610200',
        name: '铜川市',
        p_name: '陕西省',
        label: '铜川市',
        value: '铜川市',
      },
      {
        parentAdcode: '610000',
        adcode: '610300',
        name: '宝鸡市',
        p_name: '陕西省',
        label: '宝鸡市',
        value: '宝鸡市',
      },
      {
        parentAdcode: '610000',
        adcode: '610400',
        name: '咸阳市',
        p_name: '陕西省',
        label: '咸阳市',
        value: '咸阳市',
      },
      {
        parentAdcode: '610000',
        adcode: '610500',
        name: '渭南市',
        p_name: '陕西省',
        label: '渭南市',
        value: '渭南市',
      },
      {
        parentAdcode: '610000',
        adcode: '610600',
        name: '延安市',
        p_name: '陕西省',
        label: '延安市',
        value: '延安市',
      },
      {
        parentAdcode: '610000',
        adcode: '610700',
        name: '汉中市',
        p_name: '陕西省',
        label: '汉中市',
        value: '汉中市',
      },
      {
        parentAdcode: '610000',
        adcode: '610800',
        name: '榆林市',
        p_name: '陕西省',
        label: '榆林市',
        value: '榆林市',
      },
      {
        parentAdcode: '610000',
        adcode: '610900',
        name: '安康市',
        p_name: '陕西省',
        label: '安康市',
        value: '安康市',
      },
      {
        parentAdcode: '610000',
        adcode: '611000',
        name: '商洛市',
        p_name: '陕西省',
        label: '商洛市',
        value: '商洛市',
      },
    ],
    label: '陕西省',
    value: '陕西省',
  },
  {
    adcode: '620000',
    name: '甘肃省',
    children: [
      {
        parentAdcode: '620000',
        adcode: '620100',
        name: '兰州市',
        p_name: '甘肃省',
        label: '兰州市',
        value: '兰州市',
      },
      {
        parentAdcode: '620000',
        adcode: '620200',
        name: '嘉峪关市',
        p_name: '甘肃省',
        label: '嘉峪关市',
        value: '嘉峪关市',
      },
      {
        parentAdcode: '620000',
        adcode: '620300',
        name: '金昌市',
        p_name: '甘肃省',
        label: '金昌市',
        value: '金昌市',
      },
      {
        parentAdcode: '620000',
        adcode: '620400',
        name: '白银市',
        p_name: '甘肃省',
        label: '白银市',
        value: '白银市',
      },
      {
        parentAdcode: '620000',
        adcode: '620500',
        name: '天水市',
        p_name: '甘肃省',
        label: '天水市',
        value: '天水市',
      },
      {
        parentAdcode: '620000',
        adcode: '620600',
        name: '武威市',
        p_name: '甘肃省',
        label: '武威市',
        value: '武威市',
      },
      {
        parentAdcode: '620000',
        adcode: '620700',
        name: '张掖市',
        p_name: '甘肃省',
        label: '张掖市',
        value: '张掖市',
      },
      {
        parentAdcode: '620000',
        adcode: '620800',
        name: '平凉市',
        p_name: '甘肃省',
        label: '平凉市',
        value: '平凉市',
      },
      {
        parentAdcode: '620000',
        adcode: '620900',
        name: '酒泉市',
        p_name: '甘肃省',
        label: '酒泉市',
        value: '酒泉市',
      },
      {
        parentAdcode: '620000',
        adcode: '621000',
        name: '庆阳市',
        p_name: '甘肃省',
        label: '庆阳市',
        value: '庆阳市',
      },
      {
        parentAdcode: '620000',
        adcode: '621100',
        name: '定西市',
        p_name: '甘肃省',
        label: '定西市',
        value: '定西市',
      },
      {
        parentAdcode: '620000',
        adcode: '621200',
        name: '陇南市',
        p_name: '甘肃省',
        label: '陇南市',
        value: '陇南市',
      },
      {
        parentAdcode: '620000',
        adcode: '622900',
        name: '临夏回族自治州',
        p_name: '甘肃省',
        label: '临夏回族自治州',
        value: '临夏回族自治州',
      },
      {
        parentAdcode: '620000',
        adcode: '623000',
        name: '甘南藏族自治州',
        p_name: '甘肃省',
        label: '甘南藏族自治州',
        value: '甘南藏族自治州',
      },
    ],
    label: '甘肃省',
    value: '甘肃省',
  },
  {
    adcode: '630000',
    name: '青海省',
    children: [
      {
        parentAdcode: '630000',
        adcode: '630100',
        name: '西宁市',
        p_name: '青海省',
        label: '西宁市',
        value: '西宁市',
      },
      {
        parentAdcode: '630000',
        adcode: '630200',
        name: '海东市',
        p_name: '青海省',
        label: '海东市',
        value: '海东市',
      },
      {
        parentAdcode: '630000',
        adcode: '632200',
        name: '海北藏族自治州',
        p_name: '青海省',
        label: '海北藏族自治州',
        value: '海北藏族自治州',
      },
      {
        parentAdcode: '630000',
        adcode: '632300',
        name: '黄南藏族自治州',
        p_name: '青海省',
        label: '黄南藏族自治州',
        value: '黄南藏族自治州',
      },
      {
        parentAdcode: '630000',
        adcode: '632500',
        name: '海南藏族自治州',
        p_name: '青海省',
        label: '海南藏族自治州',
        value: '海南藏族自治州',
      },
      {
        parentAdcode: '630000',
        adcode: '632600',
        name: '果洛藏族自治州',
        p_name: '青海省',
        label: '果洛藏族自治州',
        value: '果洛藏族自治州',
      },
      {
        parentAdcode: '630000',
        adcode: '632700',
        name: '玉树藏族自治州',
        p_name: '青海省',
        label: '玉树藏族自治州',
        value: '玉树藏族自治州',
      },
      {
        parentAdcode: '630000',
        adcode: '632800',
        name: '海西蒙古族藏族自治州',
        p_name: '青海省',
        label: '海西蒙古族藏族自治州',
        value: '海西蒙古族藏族自治州',
      },
    ],
    label: '青海省',
    value: '青海省',
  },
  {
    adcode: '640000',
    name: '宁夏回族自治区',
    children: [
      {
        parentAdcode: '640000',
        adcode: '640100',
        name: '银川市',
        p_name: '宁夏回族自治区',
        label: '银川市',
        value: '银川市',
      },
      {
        parentAdcode: '640000',
        adcode: '640200',
        name: '石嘴山市',
        p_name: '宁夏回族自治区',
        label: '石嘴山市',
        value: '石嘴山市',
      },
      {
        parentAdcode: '640000',
        adcode: '640300',
        name: '吴忠市',
        p_name: '宁夏回族自治区',
        label: '吴忠市',
        value: '吴忠市',
      },
      {
        parentAdcode: '640000',
        adcode: '640400',
        name: '固原市',
        p_name: '宁夏回族自治区',
        label: '固原市',
        value: '固原市',
      },
      {
        parentAdcode: '640000',
        adcode: '640500',
        name: '中卫市',
        p_name: '宁夏回族自治区',
        label: '中卫市',
        value: '中卫市',
      },
    ],
    label: '宁夏回族自治区',
    value: '宁夏回族自治区',
  },
  {
    adcode: '650000',
    name: '新疆维吾尔自治区',
    children: [
      {
        parentAdcode: '650000',
        adcode: '650100',
        name: '乌鲁木齐市',
        p_name: '新疆维吾尔自治区',
        label: '乌鲁木齐市',
        value: '乌鲁木齐市',
      },
      {
        parentAdcode: '650000',
        adcode: '650200',
        name: '克拉玛依市',
        p_name: '新疆维吾尔自治区',
        label: '克拉玛依市',
        value: '克拉玛依市',
      },
      {
        parentAdcode: '650000',
        adcode: '650400',
        name: '吐鲁番市',
        p_name: '新疆维吾尔自治区',
        label: '吐鲁番市',
        value: '吐鲁番市',
      },
      {
        parentAdcode: '650000',
        adcode: '652200',
        name: '哈密地区',
        p_name: '新疆维吾尔自治区',
        label: '哈密地区',
        value: '哈密地区',
      },
      {
        parentAdcode: '650000',
        adcode: '652300',
        name: '昌吉回族自治州',
        p_name: '新疆维吾尔自治区',
        label: '昌吉回族自治州',
        value: '昌吉回族自治州',
      },
      {
        parentAdcode: '650000',
        adcode: '652700',
        name: '博尔塔拉蒙古自治州',
        p_name: '新疆维吾尔自治区',
        label: '博尔塔拉蒙古自治州',
        value: '博尔塔拉蒙古自治州',
      },
      {
        parentAdcode: '650000',
        adcode: '652800',
        name: '巴音郭楞蒙古自治州',
        p_name: '新疆维吾尔自治区',
        label: '巴音郭楞蒙古自治州',
        value: '巴音郭楞蒙古自治州',
      },
      {
        parentAdcode: '650000',
        adcode: '652900',
        name: '阿克苏地区',
        p_name: '新疆维吾尔自治区',
        label: '阿克苏地区',
        value: '阿克苏地区',
      },
      {
        parentAdcode: '650000',
        adcode: '653000',
        name: '克孜勒苏柯尔克孜自治州',
        p_name: '新疆维吾尔自治区',
        label: '克孜勒苏柯尔克孜自治州',
        value: '克孜勒苏柯尔克孜自治州',
      },
      {
        parentAdcode: '650000',
        adcode: '653100',
        name: '喀什地区',
        p_name: '新疆维吾尔自治区',
        label: '喀什地区',
        value: '喀什地区',
      },
      {
        parentAdcode: '650000',
        adcode: '653200',
        name: '和田地区',
        p_name: '新疆维吾尔自治区',
        label: '和田地区',
        value: '和田地区',
      },
      {
        parentAdcode: '650000',
        adcode: '654000',
        name: '伊犁哈萨克自治州',
        p_name: '新疆维吾尔自治区',
        label: '伊犁哈萨克自治州',
        value: '伊犁哈萨克自治州',
      },
      {
        parentAdcode: '650000',
        adcode: '654200',
        name: '塔城地区',
        p_name: '新疆维吾尔自治区',
        label: '塔城地区',
        value: '塔城地区',
      },
      {
        parentAdcode: '650000',
        adcode: '654300',
        name: '阿勒泰地区',
        p_name: '新疆维吾尔自治区',
        label: '阿勒泰地区',
        value: '阿勒泰地区',
      },
      {
        parentAdcode: '650000',
        adcode: '659001',
        name: '石河子市',
        p_name: '新疆维吾尔自治区',
        label: '石河子市',
        value: '石河子市',
      },
      {
        parentAdcode: '650000',
        adcode: '659002',
        name: '阿拉尔市',
        p_name: '新疆维吾尔自治区',
        label: '阿拉尔市',
        value: '阿拉尔市',
      },
      {
        parentAdcode: '650000',
        adcode: '659003',
        name: '图木舒克市',
        p_name: '新疆维吾尔自治区',
        label: '图木舒克市',
        value: '图木舒克市',
      },
      {
        parentAdcode: '650000',
        adcode: '659004',
        name: '五家渠市',
        p_name: '新疆维吾尔自治区',
        label: '五家渠市',
        value: '五家渠市',
      },
      {
        parentAdcode: '650000',
        adcode: '659005',
        name: '北屯市',
        p_name: '新疆维吾尔自治区',
        label: '北屯市',
        value: '北屯市',
      },
      {
        parentAdcode: '650000',
        adcode: '659006',
        name: '铁门关市',
        p_name: '新疆维吾尔自治区',
        label: '铁门关市',
        value: '铁门关市',
      },
      {
        parentAdcode: '650000',
        adcode: '659007',
        name: '双河市',
        p_name: '新疆维吾尔自治区',
        label: '双河市',
        value: '双河市',
      },
      {
        parentAdcode: '650000',
        adcode: '659008',
        name: '可克达拉市',
        p_name: '新疆维吾尔自治区',
        label: '可克达拉市',
        value: '可克达拉市',
      },
    ],
    label: '新疆维吾尔自治区',
    value: '新疆维吾尔自治区',
  },
  {
    adcode: '710000',
    name: '台湾省',
    value: '台湾省',
    label: '台湾省',
    children: [
      {
        value: '台湾',
        label: '台湾',
      },
    ],
  },
  {
    adcode: '810000',
    name: '香港特别行政区',
    children: [
      {
        parentAdcode: '810000',
        adcode: '810001',
        name: '中西区',
        p_name: '香港特别行政区',
        label: '中西区',
        value: '中西区',
      },
      {
        parentAdcode: '810000',
        adcode: '810002',
        name: '湾仔区',
        p_name: '香港特别行政区',
        label: '湾仔区',
        value: '湾仔区',
      },
      {
        parentAdcode: '810000',
        adcode: '810003',
        name: '东区',
        p_name: '香港特别行政区',
        label: '东区',
        value: '东区',
      },
      {
        parentAdcode: '810000',
        adcode: '810004',
        name: '南区',
        p_name: '香港特别行政区',
        label: '南区',
        value: '南区',
      },
      {
        parentAdcode: '810000',
        adcode: '810005',
        name: '油尖旺区',
        p_name: '香港特别行政区',
        label: '油尖旺区',
        value: '油尖旺区',
      },
      {
        parentAdcode: '810000',
        adcode: '810006',
        name: '深水埗区',
        p_name: '香港特别行政区',
        label: '深水埗区',
        value: '深水埗区',
      },
      {
        parentAdcode: '810000',
        adcode: '810007',
        name: '九龙城区',
        p_name: '香港特别行政区',
        label: '九龙城区',
        value: '九龙城区',
      },
      {
        parentAdcode: '810000',
        adcode: '810008',
        name: '黄大仙区',
        p_name: '香港特别行政区',
        label: '黄大仙区',
        value: '黄大仙区',
      },
      {
        parentAdcode: '810000',
        adcode: '810009',
        name: '观塘区',
        p_name: '香港特别行政区',
        label: '观塘区',
        value: '观塘区',
      },
      {
        parentAdcode: '810000',
        adcode: '810010',
        name: '荃湾区',
        p_name: '香港特别行政区',
        label: '荃湾区',
        value: '荃湾区',
      },
      {
        parentAdcode: '810000',
        adcode: '810011',
        name: '屯门区',
        p_name: '香港特别行政区',
        label: '屯门区',
        value: '屯门区',
      },
      {
        parentAdcode: '810000',
        adcode: '810012',
        name: '元朗区',
        p_name: '香港特别行政区',
        label: '元朗区',
        value: '元朗区',
      },
      {
        parentAdcode: '810000',
        adcode: '810013',
        name: '北区',
        p_name: '香港特别行政区',
        label: '北区',
        value: '北区',
      },
      {
        parentAdcode: '810000',
        adcode: '810014',
        name: '大埔区',
        p_name: '香港特别行政区',
        label: '大埔区',
        value: '大埔区',
      },
      {
        parentAdcode: '810000',
        adcode: '810015',
        name: '西贡区',
        p_name: '香港特别行政区',
        label: '西贡区',
        value: '西贡区',
      },
      {
        parentAdcode: '810000',
        adcode: '810016',
        name: '沙田区',
        p_name: '香港特别行政区',
        label: '沙田区',
        value: '沙田区',
      },
      {
        parentAdcode: '810000',
        adcode: '810017',
        name: '葵青区',
        p_name: '香港特别行政区',
        label: '葵青区',
        value: '葵青区',
      },
      {
        parentAdcode: '810000',
        adcode: '810018',
        name: '离岛区',
        p_name: '香港特别行政区',
        label: '离岛区',
        value: '离岛区',
      },
    ],
    label: '香港特别行政区',
    value: '香港特别行政区',
  },
  {
    adcode: '820000',
    name: '澳门特别行政区',
    children: [
      {
        parentAdcode: '820000',
        adcode: '820001',
        name: '花地玛堂区',
        p_name: '澳门特别行政区',
        label: '花地玛堂区',
        value: '花地玛堂区',
      },
      {
        parentAdcode: '820000',
        adcode: '820002',
        name: '花王堂区',
        p_name: '澳门特别行政区',
        label: '花王堂区',
        value: '花王堂区',
      },
      {
        parentAdcode: '820000',
        adcode: '820003',
        name: '望德堂区',
        p_name: '澳门特别行政区',
        label: '望德堂区',
        value: '望德堂区',
      },
      {
        parentAdcode: '820000',
        adcode: '820004',
        name: '大堂区',
        p_name: '澳门特别行政区',
        label: '大堂区',
        value: '大堂区',
      },
      {
        parentAdcode: '820000',
        adcode: '820005',
        name: '风顺堂区',
        p_name: '澳门特别行政区',
        label: '风顺堂区',
        value: '风顺堂区',
      },
      {
        parentAdcode: '820000',
        adcode: '820006',
        name: '嘉模堂区',
        p_name: '澳门特别行政区',
        label: '嘉模堂区',
        value: '嘉模堂区',
      },
      {
        parentAdcode: '820000',
        adcode: '820007',
        name: '路凼填海区',
        p_name: '澳门特别行政区',
        label: '路凼填海区',
        value: '路凼填海区',
      },
      {
        parentAdcode: '820000',
        adcode: '820008',
        name: '圣方济各堂区',
        p_name: '澳门特别行政区',
        label: '圣方济各堂区',
        value: '圣方济各堂区',
      },
    ],
    label: '澳门特别行政区',
    value: '澳门特别行政区',
  },
];

export { provienceData, geoCoordMap, regionData };
